# Generated by Django 4.2 on 2025-01-19 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('link', models.URLField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='instituciones/')),
            ],
        ),
        migrations.CreateModel(
            name='Integrante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('ocupacion', models.CharField(blank=True, max_length=255, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='integrantes/')),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Multimedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('evento', models.CharField(blank=True, max_length=255, null=True)),
                ('etiquetas', models.TextField(blank=True, null=True)),
                ('archivo', models.FileField(upload_to='multimedia/')),
            ],
        ),
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='personajes/')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('integrante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personajes', to='sitioChocobanda.integrante')),
            ],
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='obras/')),
                ('duracion', models.DurationField()),
                ('personajes', models.ManyToManyField(related_name='obras', to='sitioChocobanda.personaje')),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id_noticia', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('cuerpo', models.TextField()),
                ('fotos', models.ManyToManyField(blank=True, related_name='noticias_fotos', to='sitioChocobanda.multimedia')),
            ],
        ),
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canciones', models.TextField(blank=True, null=True)),
                ('fotos', models.ManyToManyField(blank=True, related_name='galerias_fotos', to='sitioChocobanda.multimedia')),
                ('videos', models.ManyToManyField(blank=True, related_name='galerias_videos', to='sitioChocobanda.multimedia')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('invitados', models.TextField(blank=True, null=True)),
                ('instituciones_beneficiadas', models.TextField(blank=True, null=True)),
                ('integrantes', models.ManyToManyField(related_name='eventos', to='sitioChocobanda.integrante')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='sitioChocobanda.obra')),
            ],
        ),
    ]
