# Generated by Django 5.1.6 on 2025-02-27 00:54

import cropperjs.models
import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AjustesPagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historia_chocobanda', models.TextField()),
                ('instagram_link', models.URLField(blank=True, null=True)),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('youtube_link', models.URLField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('correo_electronico', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('impacto_social', models.TextField(blank=True, null=True)),
                ('link_institucion', models.URLField(blank=True, null=True)),
                ('foto', cropperjs.models.CropperImageField(aspectratio='1.5', blank=True, dimensions=(600, 400), null=True, upload_to='instituciones/')),
            ],
        ),
        migrations.CreateModel(
            name='Integrante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('ocupacion', models.CharField(blank=True, max_length=255, null=True)),
                ('foto', cropperjs.models.CropperImageField(aspectratio='1.0', blank=True, dimensions=(200, 200), null=True, upload_to='integrantes/')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('actuales', 'Actual'), ('invitados', 'Invitado'), ('memorables', 'Memorable')], default='Actual', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Multimedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('evento', models.CharField(blank=True, max_length=255, null=True)),
                ('etiquetas', models.TextField(blank=True, null=True)),
                ('archivo', models.FileField(upload_to='multimedia/')),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id_noticia', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('cuerpo', models.TextField()),
                ('foto', cropperjs.models.CropperImageField(aspectratio='1.5', blank=True, dimensions=(600, 400), null=True, upload_to='novedades/')),
            ],
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('foto', cropperjs.models.CropperImageField(aspectratio='1.5', blank=True, dimensions=(900, 600), null=True, upload_to='obras/')),
            ],
        ),
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canciones', models.TextField(blank=True, null=True)),
                ('fotos', models.ManyToManyField(blank=True, related_name='galerias_fotos', to='sitioChocobanda.multimedia')),
                ('videos', models.ManyToManyField(blank=True, related_name='galerias_videos', to='sitioChocobanda.multimedia')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramaObra',
            fields=[
                ('obra', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='programa_obra', serialize=False, to='sitioChocobanda.obra')),
                ('programa', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='GaleriaObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', cropperjs.models.CropperImageField(aspectratio='1.3333333333333333', blank=True, dimensions=(1024, 768), null=True, upload_to='galeria_obra/')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria_obra', to='sitioChocobanda.obra')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField(default='00:00:00')),
                ('invitados', models.TextField(blank=True, null=True)),
                ('instituciones_beneficiadas', models.TextField(blank=True, null=True)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='sitioChocobanda.obra')),
            ],
        ),
        migrations.CreateModel(
            name='CancionObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('duracion', models.DurationField(blank=True, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='canciones/')),
                ('enlace', models.URLField(blank=True, null=True)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canciones_obra', to='sitioChocobanda.obra')),
            ],
        ),
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('foto', cropperjs.models.CropperImageField(aspectratio='1.5', blank=True, dimensions=(300, 200), null=True, upload_to='personajes/')),
                ('integrante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personajes', to='sitioChocobanda.integrante')),
            ],
        ),
        migrations.CreateModel(
            name='VideoObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('duracion', models.DurationField(blank=True, null=True)),
                ('enlace', models.URLField()),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos_obra', to='sitioChocobanda.obra')),
            ],
        ),
    ]
