# Generated by Django 4.2 on 2025-03-04 22:53

import cropperjs.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitioChocobanda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ajustespagina',
            name='foto_principal',
            field=cropperjs.models.CropperImageField(aspectratio='1.7777777777777777', blank=True, dimensions=(1280, 720), null=True, upload_to='ajustes/'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='foto',
            field=cropperjs.models.CropperImageField(aspectratio='1.7777777777777777', blank=True, dimensions=(1280, 720), null=True, upload_to='obras/'),
        ),
        migrations.AlterField(
            model_name='personaje',
            name='foto',
            field=cropperjs.models.CropperImageField(aspectratio='1.7777777777777777', blank=True, dimensions=(1280, 720), null=True, upload_to='personajes/'),
        ),
        migrations.DeleteModel(
            name='Galeria',
        ),
    ]
