# Generated by Django 4.2 on 2025-01-19 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitioChocobanda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrante',
            name='estado',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
