# Generated by Django 4.2 on 2025-01-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitioChocobanda', '0002_integrante_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrante',
            name='estado',
            field=models.CharField(choices=[('actuales', 'Actual'), ('invitados', 'Invitado'), ('memorables', 'Memorable')], default='Actual', max_length=255),
        ),
    ]
