# Generated by Django 5.1 on 2025-01-21 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitioChocobanda', '0002_integrante_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obra',
            name='duracion',
        ),
        migrations.RemoveField(
            model_name='obra',
            name='personajes',
        ),
        migrations.RemoveField(
            model_name='personaje',
            name='descripcion',
        ),
        migrations.AlterField(
            model_name='integrante',
            name='estado',
            field=models.CharField(choices=[('actuales', 'Actual'), ('invitados', 'Invitado'), ('memorables', 'Memorable')], default='Actual', max_length=255),
        ),
        migrations.CreateModel(
            name='GaleriaFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='galeria_fotos/')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria_fotos', to='sitioChocobanda.obra')),
            ],
        ),
    ]
