# Generated by Django 5.1 on 2025-03-05 22:48

import cropperjs.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitioChocobanda', '0002_ajustespagina_foto_principal_alter_obra_foto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='foto',
            field=cropperjs.models.CropperImageField(aspectratio='1.7777777777777777', blank=True, dimensions=(1280, 720), null=True, upload_to='novedades/'),
        ),
    ]
