# Generated by Django 5.1 on 2025-03-08 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitioChocobanda', '0003_alter_noticia_foto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ajustespagina',
            options={'verbose_name': 'Ajuste de Página', 'verbose_name_plural': 'Ajustes de Página'},
        ),
        migrations.AlterModelOptions(
            name='institucion',
            options={'verbose_name_plural': 'Instituciones'},
        ),
        migrations.AlterModelOptions(
            name='noticia',
            options={'verbose_name': 'Novedad', 'verbose_name_plural': 'Novedades'},
        ),
    ]
