# Generated by Django 4.2 on 2025-01-28 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitioChocobanda', '0003_alter_integrante_estado'),
        ('sitioChocobanda', '0004_ajustespagina_and_more'),
    ]

    operations = [
    ]
