# Generated by Django 5.1 on 2025-01-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitioChocobanda', '0005_evento_hora'),
    ]

    operations = [
        migrations.CreateModel(
            name='Novedad',
            fields=[
                ('id_novedad', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('cuerpo', models.TextField()),
                ('fotos', models.ManyToManyField(blank=True, related_name='novedades_fotos', to='sitioChocobanda.multimedia')),
            ],
        ),
        migrations.DeleteModel(
            name='Noticia',
        ),
    ]
