# Generated by Django 5.1 on 2025-01-28 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitioChocobanda', '0006_novedad_delete_noticia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novedad',
            name='fotos',
        ),
        migrations.AddField(
            model_name='novedad',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='novedades/'),
        ),
    ]
