# Generated by Django 5.1 on 2025-01-28 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitioChocobanda', '0007_remove_novedad_fotos_novedad_foto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Novedad',
            new_name='Noticia',
        ),
        migrations.RenameField(
            model_name='noticia',
            old_name='id_novedad',
            new_name='id_noticia',
        ),
    ]
