# Generated by Django 4.2 on 2025-01-28 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitioChocobanda', '0005_merge_20250128_1343'),
        ('sitioChocobanda', '0008_rename_novedad_noticia_and_more'),
    ]

    operations = [
    ]
