# Generated by Django 5.1 on 2025-01-31 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitioChocobanda', '0009_merge_20250128_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramaObra',
            fields=[
                ('obra', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='programa_obra', serialize=False, to='sitioChocobanda.obra')),
                ('programa', models.TextField()),
            ],
        ),
    ]
