# Generated by Django 5.1 on 2025-02-04 19:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitioChocobanda', '0010_programaobra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programaobra',
            name='programa',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.DeleteModel(
            name='GaleriaInstitucion',
        ),
    ]

# Generated by Django 5.1 on 2025-02-04 18:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitioChocobanda', '0010_programaobra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programaobra',
            name='programa',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.DeleteModel(
            name='GaleriaInstitucion',
        ),
    ]
