# Generated by Django 4.2 on 2025-02-09 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitioChocobanda', '0009_merge_20250128_1716'),
        ('sitioChocobanda', '0011_alter_programaobra_programa_and_more'),
    ]

    operations = [
    ]
