# Generated by Django 5.1 on 2025-02-18 01:01

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitioChocobanda', '0012_merge_20250209_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programaobra',
            name='programa',
            field=tinymce.models.HTMLField(),
        ),
    ]
